---
- name: Wait for ssh connection
  hosts: all
  gather_facts: False
  tasks:
    - name: Ensure ssh port open
      wait_for:
        port: 22
        delay: 30
        timeout: 50
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python3
#Prod server
- name: Run buildapp hello-1.0.war
  hosts: all
  become: yes
  tasks: 
    - name: Update repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install default-jdk tomcat
      apt:
        pkg:
          - default-jdk
          - tomcat9

    - name: Copy .war from local host to remote host
      copy:
        src: /tmp/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/
                

